server:
  error:
    include-message: always
spring:
  main:
    allow-bean-definition-overriding: true
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/javaforest
    username: postgres
    password: root


  flyway:
    url: jdbc:postgresql://localhost:5432/javaforest
    locations: classpath:db/migration
    enabled: true
    user: postgres
    password: root
    baseline-version: 1
    sql-migration-prefix: V
    sql-migration-suffixes: .sql
    baseline-on-migrate: true

app:
  jjwt:
    secret: ThisIsSecretForJWTHS512SignatureAlgorithmThatHave512bitsKeySize
    access_expiration: 43200
    refresh_expiration: 172800
    tokenType: Bearer
    password:
      encoder:
        secret: myjwtsecret
        iteration: 33
        keylength: 256